[tool.uv]
no-build-isolation-package = ["torch_scatter"]
managed = true
default-groups = ["physicsnemo"]

# The dependency-group tree is critically important for physicsnemo.
# Here, we list dependencies for each physicsnemo pacakge.  Optional
# dependencies are listed with the name `package`-extras.  Dependencies
# are chained together: for example, everything in core is a dep of the
# entire repo, but utils-extra only shows up for subsequent *-extra
# lists.
# 
# We do this to ensure a consistent install path for targeted levels of the
# repository.  If you just want the distributed manager, for example, you can
# target `distributed` instead of `physicsnemo` and you're up and running.
# 
# These lists are the SINGLE SOURCE OF TRUTH.  Models are also included
# below, to make single-model installation easier.
# 
# In general, we do not draw a finer line than "required" and "extra".
# So, physicsnemo.nn's requirements do not include scipy and cuml, but the
# "extra" version includes BOTH. 

[dependency-groups]
core = [
    "torch>=2.4.0",
    "tqdm>=4.60.0",
    "requests",
    "GitPython",
]
# no core-extras
distributed = [
    "numpy>=1.22.4",
    {include-group = "core"}
]
# no distributed-extras
utils = [
    "termcolor",
    "onnx",
    "pandas",
    "nvtx",
    {include-group = "distributed"},
]
utils-extras = [
    "wandb",
    "mlflow",
    "line_profiler",
    "vtx",
    "warp-lang",
]
nn = [
    "einops",
    "warp-lang",
    {include-group= "utils"}
]
nn-extras = [
    "cuml",
    "scipy",
    "cupy",
]
physicsnemo = [
    {include-group = "nn"},
    {include-group = "utils"},
]
physicsnemo-extras = [
    {include-group = "physicsnemo"},
    {include-group = "nn-extras"},
    {include-group = "utils-extras"},
]
dev = [
    "pytest",
    "import-linter"
]

[project]
name = "nvidia-physicsnemo"
authors = [
  { name="NVIDIA PhysicsNeMo Team"},
]
description = "A deep learning framework for AI-driven multi-physics systems"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/NVIDIA/physicsnemo"
Documentation = "https://docs.nvidia.com/physicsnemo/index.html#core"
Issues = "https://github.com/NVIDIA/physicsnemo/issues"
Changelog = "https://github.com/NVIDIA/physicsnemo/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["physicsnemo"]


[tool.ruff]
# Enable flake8/pycodestyle (`E`), Pyflakes (`F`), flake8-bandit (`S`),
# isort (`I`), and performance 'PERF' rules.
lint.select = ["E", "F", "S", "I", "PERF"]
lint.fixable = ["I"]

# Never enforce `E402`, `E501` (line length violations),
# and `S311` (random number generators)
lint.ignore = ["E501", "S311"]

# Exclude the docs and experimental folders (this applies to both lint and format)
exclude = ["docs", "physicsnemo/experimental"]

[tool.ruff.lint.per-file-ignores]
# Ignore `F401` (import violations) in all `__init__.py` files, and in `docs/*.py`.
"__init__.py" = ["F401"]
"docs/*.py" = ["F401"]

# Ignore `S101` (assertions) in all `test` files.
"test/*.py" = ["S101"]
